.TH SNOOZENODE 1 "Apr  30, 2012"
.SH NAME
 snoozenode \- starts the Snooze node
.SH SYNOPSIS
.B snoozenode
.RI "[configFile] [logFile]"
.SH DESCRIPTION
This manual page documents briefly the
.B snoozenode
command.
.PP
\fBsnoozenode\fP is the core system management component of the Snooze cloud management
framework.
.SH AUTHOR
Eugen Feller <eugen.feller@inria.fr>. See http://snooze.inria.fr
.PP
This manual page was written by Eugen Feller .
